### 18e november

# Intro

- Den nya boken kommer användas ganska mycket, men inte obligatoriskt att skaffa
    - Kolla författarens github för uppdaterade exempel.
- Första veckan:
    - MLP - Multi Layered Perceptrons
- Examineringsformerna:
    - Labb
        - Enskild
        - Spela PacMan
    - Projekt
        - I grupp (3-5st)
        - Individuell video redovisning.

# Lite matte

Begrepp:
- Tensor
    - generaliserade vektorer/matriser
    - rank:
        - en 0-tensor har rank 0 == ett tal tex 5
        - en 1-tensor (rank1) == lista av tal
        - 2-tensor (rank2) == en tabell/matris
        - 3-tensor (rank3) == flera matriser liggandes på varandra likt en kub.
        - osv
    - Har vi ett NN med 20 lager har vi en rank20 tensor.
    - En kolonnvektor anger bilden längs en viss axel.
    - En matris är en linjär avbildning, alltså en funktion.
        - Konvolvering == algoritm på tensor
            - Kernel (INTE OS ELLER SVM)
                - Ett "fönster" i vår matris
                - Ett sätt att dela upp uträkningen av matrisen
            - Andra sätt:
                - determinanter
                - med mera
        - Förändring
            - 2D: y = kx + m
                - Derivata: dy/dx, y' | y = x^2 + 2x -1, 2x +2
            3D: x^2 + y^2 + z^2 = 1
                - Derivata: näää orkar inte skriva detta. Kolla stream.

Hur lager ser ut:
- Output =
    - activation (dot(*w*eights, input) + *b*ias)
- Utan "activation" blir det en linjär funktion. Om något är icke-linjärt så blir allt icke-linjärt!

In [1]:
# Datan behöver också vara en tensor

import numpy as np

x = np.array(12) # noll dimensionell tensor
x

array(12)

In [3]:
x = np.array([12, 3, 6, 14, 7]) # 1 dimensionell tensor
x, x.ndim

(array([12,  3,  6, 14,  7]), 1)

In [4]:
x = np.array([[5, 78, 2, 34, 0], [1, 3, 2, 5, 2]]) # 2 dimensionell tensor
x, x.ndim

(array([[ 5, 78,  2, 34,  0],
        [ 1,  3,  2,  5,  2]]),
 2)

In [7]:
x = np.array([ # 3 dimensionell tensor
        [
            [5, 78, 2, 34, 0],
            [1, 3, 2, 5, 2]
    ],
        [
            [5, 78, 2, 34, 0],
            [1, 3, 2, 5, 2]
    ],
        [
            [5, 78, 2, 34, 0],
            [1, 3, 2, 5, 2]
    ]
])

x, x.ndim

(array([[[ 5, 78,  2, 34,  0],
         [ 1,  3,  2,  5,  2]],
 
        [[ 5, 78,  2, 34,  0],
         [ 1,  3,  2,  5,  2]],
 
        [[ 5, 78,  2, 34,  0],
         [ 1,  3,  2,  5,  2]]]),
 3)